### ISSUE TITLE
 Add user preference for intro skipping method

### ISSUE THREAD

**Issue by jumoog** [intro-skipper/intro-skipper#126]
Would be nice if each user could choose if they want auto skip or just button.

~~Also, would be good if we could specify certain clients where it would automatically skip, for people with Android TV's who don't want to recompile the whole app, if you just set it to skip intro, you won't need the button.~~

from https://github.com/ConfusedPolarBear/intro-skipper/issues/18

**Comment by AbandonedCart** [comment]
All you need is the client default. Everything else is done already.

**Comment by jumoog** [comment]
yeah its not hard todo

**Comment by AbandonedCart** [comment]
Wasn't the Android TV part the missing one? We already have options to select the method manually.

**Comment by jumoog** [comment]
Yes, but my sister, for example, loves to watch intros on her Android TV 😂.
