### ISSUE TITLE
[Feature request] automatic skip only when the client does not support the use of the skip button

### ISSUE THREAD

**Issue by jumoog** [intro-skipper/intro-skipper#206]
Known Clients

| **AppName**             | **Support Button** |
|-------------------------|--------------------|
| `Jellyfin Web`             | x                  |
| `Android TV`               |                    |
| `Jellyfin Android`         | x                  |
| `Jellyfin Tizen (Samsung)` | x                  |
| `Findroid`                 | x (native)         |
| `Jellyfin Media Player` | If enabled         |
|`Browser PiP`              |                    |

**Comment by jumoog** [comment]
This means that it will check for the AppName, and only skip automatically if the AppName is `Android TV`.

**Comment by Vergil365** [comment]
Kodi support would be nice too :)

**Comment by Dnkhatri** [comment]
There is also jellyfin mpv shim. https://github.com/jellyfin/jellyfin-mpv-shim

**Comment by AbandonedCart** [comment]
> There is also jellyfin mpv shim. https://github.com/jellyfin/jellyfin-mpv-shim

That shouldn't require skipping automatically.

**Comment by rlauuzo** [comment]
I think people only want autoskipping on devices that don't support a skip button, since enabling autoskip forces skipping on all devices. Additionally, someone on Discord mentioned that on Android TV, skipping by pressing the enter/OK key still works, but the button itself isn't visible.

**Comment by AbandonedCart** [comment]
I would assume the button would have worked. Android typically translates the gamdpad and controller keys into keyboard equivalents for processing.

**Comment by JamsRepos** [comment]
> I think people only want autoskipping on devices that don't support a skip button, since enabling autoskip forces skipping on all devices.

This is correct, I had originally mentioned this in the Discord for that exact reason. As for someone who swaps between Android TV and my computer, i'd rather skip myself on my computer than have it automatically force me to skip, whereas on the Android TV app, no skip button is present.

**Comment by AbandonedCart** [comment]
@jumoog It may be time to abandon trying to force an auto skip for Android TV and consider an alternate approach. It hasn't gained any support and I remember it being proposed and shot down at least once before.

**Comment by jumoog** [comment]
Another approach would be to insert chapters. Or we could modify the Android TV app, but I really don't want to do that.

**Comment by AbandonedCart** [comment]
Is there any reason the hardware buttons aren't a viable option?

**Comment by JamsRepos** [comment]
> Is there any reason the hardware buttons aren't a viable option?

Unless you force a message to the client saying "Press this button on your controller to skip" consistently each time an intro segment appears, I don't see this as a viable option. You can't really expect users to know about something like that when they're not told. Although, i'm not too sure what the issue you're referring to for auto skipping is, possibly to do with web hooks? Which my solution would also require.

**Comment by JamsRepos** [comment]
> The offical Jellyfin Android TV App dont use the server website. So there is no button you can press.

My thoughts exactly, it's almost it's own bespoke application. I think there's major confusion going on inside this feature request.

**Comment by AbandonedCart** [comment]
Does Android TV not have a remote / controller anymore?

**Comment by jumoog** [comment]
> Does Android TV not have a remote / controller anymore?

We have a remote control, but nothing to click/skip. This is why we need to send a seek command.

**Comment by AbandonedCart** [comment]
And didn't @rlauuzo say that executing the button worked, but it was the **UI** component that was missing.

**Comment by jumoog** [comment]
> And didn't @rlauuzo say that executing the button worked, but it was the **UI** component that was missing.

Maybe he meant the Android app? This may work if you sideload the app, but you can only download the Android TV app from the Play Store.

**Comment by AbandonedCart** [comment]
If this really is the situation, the Android TV app hardly seems worth downloading.

**Comment by jumoog** [comment]
Well, I bought a cheap Google Chromecast 4k and the Android TV app is the only one you can download 😂

**Comment by jumoog** [comment]
thats the current Intro Skip button situation https://github.com/jellyfin/jellyfin-androidtv/issues/1800

**Comment by rlauuzo** [comment]
> > And didn't @rlauuzo say that executing the button worked, but it was the **UI** component that was missing.
> 
> Maybe he meant the Android app? This may work if you sideload the app, but you can only download the Android TV app from the Play Store.

Someone on Discord mentioned that it works on their Fire TV Stick even though the button doesn't appear. I don't have an Android TV device to test it myself.

**Comment by JamsRepos** [comment]
I will test it shortly, I am about to stick a show on anyways.

**Comment by jumoog** [comment]
I dont see any API calls for our Plugin in the code. Maybe that person used a webview?

**Comment by JamsRepos** [comment]
Can confirm it does not exist on Android TV client.

**Comment by AbandonedCart** [comment]
I'm looking into what they're using to see what options are available.

**Comment by ethaldeman** [comment]
Should  add the [Roku](https://github.com/jellyfin/jellyfin-roku) app and [Swiftfin](https://github.com/jellyfin/Swiftfin) ?

**Comment by JamsRepos** [comment]
I would assume webOS too, with third party clients such as Infuse (although I’m not sure if the API is listened to on Infuse).

**Comment by jumoog** [comment]
> I would assume webOS too, with third party clients such as Infuse (although I’m not sure if the API is listened to on Infuse). 

webOS uses the Jellyfin Server Webinterface. So it has a skip button

**Comment by JamsRepos** [comment]
> > I would assume webOS too, with third party clients such as Infuse (although I’m not sure if the API is listened to on Infuse).
> 
> webOS uses the Jellyfin Server Webinterface. So it has a skip button

Oh nice, didn’t know that.

**Comment by Brramble** [comment]
Daft opinion: what about a selection where you can opt in auto-skipping for selected devices? So instead, you dont need to catch all in your code, the user could just chose in their settings? IDK.

**Comment by AbandonedCart** [comment]
> Daft opinion: what about a selection where you can opt in auto-skipping for selected devices? So instead, you dont need to catch all in your code, the user could just chose in their settings? IDK.

https://github.com/jumoog/intro-skipper/pull/208#issuecomment-2207682497
Rest assured, that was already proposed.

**Comment by Schaka** [comment]
> > I would assume webOS too, with third party clients such as Infuse (although I’m not sure if the API is listened to on Infuse).
> 
> webOS uses the Jellyfin Server Webinterface. So it has a skip button

Same goes for Tizen. It's not officially on the store, but maintained and people use it.

There's also Jellyfin for Kodi and JellyCon for the client list.
Neither can show the button, to the best of my knowledge, but both support automatic skipping.

**Comment by AbandonedCart** [comment]
Kodi is already added. You can see what's currently listed in #208

**Comment by dredstone1** [comment]
Add picture in picture mode to the table above

**Comment by dredstone1** [comment]
Findroid have skip button built-in

**Comment by Euphoriyy** [comment]
> > > I would assume webOS too, with third party clients such as Infuse (although I’m not sure if the API is listened to on Infuse).
> > 
> > 
> > webOS uses the Jellyfin Server Webinterface. So it has a skip button
> 
> Same goes for Tizen. It's not officially on the store, but maintained and people use it.
> 
> There's also Jellyfin for Kodi and JellyCon for the client list. Neither can show the button, to the best of my knowledge, but both support automatic skipping.

I actually do use Jellyfin on a Tizen TV with support for the skip button by setting up a custom module for [TizenBrew](https://github.com/reisxd/TizenBrew) (A Tizen app that lets you run your own Tizen apps without installation hassle). I made it according to the standard set [here (specifically an application module)](https://github.com/reisxd/TizenBrew/blob/main/docs/MODULES.md#application-modules) and made it link to my Jellyfin server link. You can do the same by following what I did in my [repository](https://github.com/Euphoriyy/jellyfin-tizen) and just changing the link to your own Jellyfin server in the package.json.
