### ISSUE TITLE
[Feature Request] Add support for movies

### ISSUE THREAD

**Issue by BLACK4585** [intro-skipper/intro-skipper#250]
Altough it is not (so easy) possible to automatically detect intros/outros on movies since you only have one media file you can't compare, it would still be nice to show them on the plugin config page. So you would be able to set those timestamps manually. Maybe the outro detection is possible using the blackframe analyzer..
As a consequence, the "Next episode" button at the end could then just close the player and be called "End movie" or so.

Maybe a bigger project for the future, not sure.
Thank you in advance!

**Comment by AbandonedCart** [comment]
Detection of the intro would definitely be nearly impossible in movies that don’t follow a conventional TV opening, but manual entry isn’t unreasonable and chapter detection would also be a consideration. Credits probably could be detected using every method except audio comparison. It is definitely something that should be its own subsection to avoid confusion, though.

**Comment by jumoog** [comment]
It is not difficult to allow the times to be set manually. However, I still don't see the advantage. There is no intro for films and you can easily see the credits when they are playing. Also, you usually only watch the film once. So even if you have an intro, you only watch it once anyway.

**Comment by BLACK4585** [comment]
That's not fully true. Often older films have like an intro, where the credits are played before and not after the movie itself. And although I might watch the movie once, other users on my JF Server might watch it too. So with this feature, you could make the skipping process for them easier.
Also, I got inspired by Netflix for this, since they also show you different movies as soon as the credits begin. This is not natively available in JF, but so the viewer could have a clearer information when the movie ends and can then easily go back to the main menu with a click of a button which would appear then.
Also regarding your argument that you can clearly see the credits when they are played, this also applies to show, or not? Otherwise, a black frame analyzer wouldn't work.

**Comment by AbandonedCart** [comment]
> Also regarding your argument that you can clearly see the credits when they are played, this also applies to show, or not? 

Basically anything animated falls into "or not" along with shows that play the credits over a scene. Some cleverly blend the end of the show into it. The only method that works 100% of the time is chapters and the issue there is not all files have them or label them well. The reason there are multiple methods of detection is because none of them are 100% reliable.
