### ISSUE TITLE
Jellyfin (10.10) media segments API

### ISSUE THREAD

**Issue by jumoog** [intro-skipper/intro-skipper#262]
We know it is coming.

**Comment by AbandonedCart** [comment]
My money is on not adapting to it for a version or two. Seems like it'll be a little rough out of the gate.

**Comment by AbandonedCart** [comment]
Linking this to #268

**Comment by jumoog** [comment]
First step done, next step use the new API

**Comment by AbandonedCart** [comment]
@anthonylavado What’s the process for updating an existing record? Is it updated by create, does it need to be deleted and recreated? It doesn’t seem like there is a separate endpoint for that.

**Comment by AbandonedCart** [comment]
Further research looks like create can also update. It may be worth suggesting the addition of an update endpoint even if it just calls create under the hood.

**Comment by jumoog** [comment]
@anthonylavado It would be helpful to have an option to write segments in bulk

**Comment by JPVenson** [comment]
The current state of the MediaSegment system plans you to implement the IMediaSegmentProvider interface and then you get called and expected to return the full list of all segments for a particular BaseItem. The MediaSegmentService will then purge all old segments and replace them with whatever you have returned from that plugin.

**Comment by AbandonedCart** [comment]
> The current state of the MediaSegment system plans you to implement the IMediaSegmentProvider interface and then you get called and expected to return the full list of all segments for a particular BaseItem. The MediaSegmentService will then purge all old segments and replace them with whatever you have returned from that plugin.

So in contrast to normal plugins the essentially collaborate with the same data, this also relies heavily on the user to be aware of having more than one plugin with the same purpose to avoid it becoming a race to see which plugin submits the data last at the risk of colliding during the process.

**Comment by JPVenson** [comment]
Currently yes. We already identified this issue and tried to implement a working fix before the feature freeze
https://github.com/orgs/jellyfin/projects/63?pane=issue&itemId=80794385
Which due to some sickness by me did not made the cut. For all intents and purposes however, that is the "designed" way how the plugin should function. No over http or its own triggers but embedded into the JF architecture and run as a plugin via the interface.

**Comment by AbandonedCart** [comment]
Seems like a really formal way of saying “adapt a flawed method that everyone knows is flawed and then fix it later”

You’ll have to excuse me for not sugar coating it, but it’s easier to get right to the point.

**Comment by JPVenson** [comment]
i dont see it that way, the method is neither flawed nor buggy.

Its the first implementation of that very big topic and you are also welcome to help with it by contributing code changes.

The interface is designed in a way that the future change will not require any changes from you if you dont want to adapt to the new changes and currently i dont see any issues with that anyway as we dont even have competing plugins.

**Comment by AbandonedCart** [comment]
> Its the first implementation of that very big topic and you are also welcome to help with it by contributing code changes.

> My money is on not adapting to it for a version or two. Seems like it'll be a little rough out of the gate.

I consider there being two separate plugins that currently serve the same task as a potential issue. We aren’t *competing* unless someone ends up installing both. I consider it *flawed* to perform an update by erasing and replacing the entire data set.

It’s not meant to be offensive. As I said, I’m just not sugar coating it.

**Comment by AbandonedCart** [comment]
The logical route would likely be to add support for the official API as a secondary task alongside the current functionality, but not necessarily depend on it until it seems safe to drop the current design. After all, users can disable the UI and only use the backend already.

**Comment by JPVenson** [comment]
Please look at the meta discussion and the project board for this. This whole discussion is a bit late as we were planning the whole infastructure for the last 6 months. 

The delete and recreate method is not flawed but the easiest way to get where we want to be currently. The discussion about how media segments are build is also not best made here, but in either the meta discussion or a new one on the JF repro so other can also chime in and it does not get burried in this plugin.

I can only advice you to go the official and designed way by using the `IMediaSegmentProvider` as this is really the only place that we will support for plugins and media segments in the long run.

**Comment by AbandonedCart** [comment]
Thanks for the advice.

**Comment by AbandonedCart** [comment]
Since the remainder of the discussion is internal and steps are already being taken to prepare. I’m going to go ahead and close this issue.
