### ISSUE TITLE
Batch modification Suggestion

### ISSUE THREAD

**Issue by HomeQi** [intro-skipper/intro-skipper#264]
Hopefully, we can add bulk modifications to identify problematic episodes, So We can quickly modify episodes that identify inaccuracies, Currently there is only the ability to compare the differences between two episodes and modify them, I hope developers will consider my suggestions.Thanks!

**Comment by HomeQi** [comment]
It may be possible to consider modifying a specific episode and doing similar analysis and modification on other content under the same episode.

**Comment by AbandonedCart** [comment]
You can edit individual episodes through the episode details, but batch editing will most likely only be useful when every episode is exactly the same.

**Comment by HomeQi** [comment]
> You can edit individual episodes through the episode details, but batch editing will most likely only be useful when every episode is exactly the same.

You're right.Some episodes are not accurate enough to identify, and I want to be able to do the same for other media files in the same episode.That's my problem right now.

**Comment by AbandonedCart** [comment]
If you are on 10.9.X, the plugin has editing right in the episode details, which will be a lot easier than it sounds. The plugin editor is a bit “clunky” and tedious, though. That is something I won’t deny for a second.

**Comment by HomeQi** [comment]
> If you are on 10.9.X, the plugin has editing right in the episode meta, which will be a lot easier than it sounds. The plugin editor is a bit “clunky” and tedious, though. That is something I won’t deny for a second.

I tried modifying the configuration to retrieve it, But the results are not ideal, the recognition is missing about 10 seconds.So I can only continue to manually modify the fingerprint, let me a little disappointed, but still thank the developer very much! you are the best.

**Comment by rlauuzo** [comment]
You might want to check if this makes a difference: [GitHub Actions Run](https://github.com/jumoog/intro-skipper/actions/runs/10646610220?pr=203).
