### ISSUE TITLE
[Feature request]: Add customization for the context menu in the video player

### ISSUE THREAD

**Issue by Gauvino** [intro-skipper/intro-skipper#275]
### Describe the feature request

Could it be possible to add like the skip button, credits button and auto-skip a customization field in the settings of the extensions ?

**Comment by AbandonedCart** [comment]
This is already being discussed. Unfortunately, it is also an incremental process, so features have to be finished before they can be configured.

**Comment by AbandonedCart** [comment]
Implemented by https://github.com/intro-skipper/intro-skipper/pull/263
