### ISSUE TITLE
Contributing to documentation

### ISSUE THREAD

**Issue by AbandonedCart** [intro-skipper/intro-skipper#282]
To make it easier to quickly find help, the readme documentation and troubleshooting has moved to the wiki. If you would like to contribute, submit changes to https://github.com/jumoog/intro-skipper.wiki.git

The table of contents is located in `_Sidebar` and should follow the same format of

```
[Item Name][reference]

[reference]: *full address of url*
```

**Comment by jumoog** [comment]
https://github.com/jumoog/intro-skipper-wiki

**Comment by jumoog** [comment]
i invited you

**Comment by AbandonedCart** [comment]
That won’t link to the repository, though. The current one appears as the wiki tab.

**Comment by jumoog** [comment]
i can't create a `intro-skipper.wiki` repo

**Comment by AbandonedCart** [comment]
It already exists

**Comment by AbandonedCart** [comment]
![IMG_0213](https://github.com/user-attachments/assets/8dc5e4c5-ef41-492d-815c-585dcac2a4dc)

Bottom right of the page.
