### ISSUE TITLE
test moving to new org

### ISSUE THREAD

**Issue by jumoog** [intro-skipper/intro-skipper#294]
I moved  https://github.com/jumoog/intro-skipper-test to https://github.com/intro-skipper/intro-skipper-test

and the old URL is still working

https://raw.githubusercontent.com/jumoog/intro-skipper-test/refs/heads/master/manifest.json

todo more tests

**Comment by AbandonedCart** [comment]
You get like a month of redirects or something like that

**Comment by jumoog** [comment]
Updates to the manifest.json file in the new location will not be updated for the old URL.

**Comment by AbandonedCart** [comment]
Weird. It should redirect, but it could be because it's technically an api call.

**Comment by jumoog** [comment]
ok cool it works now.. maybe just takes some time

**Comment by jumoog** [comment]
> If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository.

There is no time limit https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by jumoog** [comment]
Another source: https://github.com/orgs/community/discussions/22669#discussioncomment-3237667

**Comment by AbandonedCart** [comment]
They must have updated it. In the past, the redirect would expire. Also keep in mind that it is a redirect, so hopefully every manner of Jellyfin handles redirects and doesn’t toss them back as a 301 (like Android’s default behavior)

**Comment by jumoog** [comment]
I dont get a redirect (tested with curl)

**Comment by jumoog** [comment]
```bash
curl -vv https://raw.githubusercontent.com/jumoog/intro-skipper-test/master/manife
st.json
```

**Comment by AbandonedCart** [comment]
Yeah. What I was talking about is the releases.

**Comment by jumoog** [comment]
> Yeah. What I was talking about is the releases.

Lucky change those URLs very easily

**Comment by AbandonedCart** [comment]
Yeah. The only catch is having it ready at the same time you transfer so it’s seamless.

**Comment by jumoog** [comment]
done
