### ISSUE TITLE
Automatically Skip Intros not skipping for unsupported clients (Infuse, Swiftfin - iOS)

### ISSUE THREAD

**Issue by seanob86** [intro-skipper/intro-skipper#311]
### Self service debugging

- [X] Jellyfin is updated (10.9.11) and my permissions are correct (or I did not use Docker)

### Describe the bug

Automatically skip intros is enabled as the intention is to skip for unsupported clients on Apple TV and iOS iPhone and iPad. Confirmed that intro time stamps exist for the episodes playing on the unsupported client i.e. clients which can't display the skip intro button.

The skip intro button displays and works for jellyfin / web player, and also auto skip works there. But for Infuse and Swiftfin the auto skip is not working and intros play right through.

Version of plugin is: 1.0.0.1.
Docker Mod: ghcr.io/jumoog/intro-skipper
Jellyfin version: 10.9.11 - Docker using lscr.io/linuxserver/jellyfin:latest image

**Troubleshooting:**

- Have cleared the skipper cache.
- Reinstalled the plugin (first removed all plugin directories in docker persistent cache).
- Restarted jellyfin
- Cleared client, Infuse/swiftfin cache
- Reinstalled client
- Rescanned library
- Tested on other devices - iPhone, iPad and Apple TV.
- Selected all clients on 'Auto Skip Client List.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

lscr.io/linuxserver/jellyfin:latest

### Operating System

Unraid

### Support Bundle

```shell
* Jellyfin version: 10.9.11
* Plugin version: 1.0.0+f0527fa888bf
* Queue contents: 654 episodes, 79 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by jumoog** [comment]
See https://github.com/intro-skipper/intro-skipper/issues/168

> 
> If you can't see this buttons in the dashboard:
> 
> ![grafik](https://github.com/jumoog/intro-skipper/assets/5268791/e3a5b24c-5107-496a-ac29-2e84a42d3cb7)
> 
> autoskip won't work either.

**Comment by seanob86** [comment]
> See #168
> 
> > If you can't see this buttons in the dashboard:
> > ![grafik](https://private-user-images.githubusercontent.com/5268791/338102284-e3a5b24c-5107-496a-ac29-2e84a42d3cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjgzOTksIm5iZiI6MTcyNzE2ODA5OSwicGF0aCI6Ii81MjY4NzkxLzMzODEwMjI4NC1lM2E1YjI0Yy01MTA3LTQ5NmEtYWMyOS0yZTg0YTQyZDNjYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDg1NDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTUxYWRkNTU3OTc0OTcxZTFhZWU5YWExM2VlZDVmZjgyZTkwZjJjNDFjMmY1MzM0YmRmNGQ5NjI4ZGQzNGU2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jr63zASMpFxzNtNo59Pb1HCw-kliwOB53iDNe0MM1_U)
> > autoskip won't work either.

Ahh I see! Was not aware of that 😞 
Swiftfin and Infuse clients don’t produce those controls in the dashboard unfortunately. Is this something only jellyfin project can fix?

**Comment by jumoog** [comment]
Im not sure. Sorry
