### ISSUE TITLE
[Bug]: Status NotSupported

### ISSUE THREAD

**Issue by Samk19** [intro-skipper/intro-skipper#312]
### Self service debugging

- [X] Jellyfin is updated (10.9.11) and my permissions are correct (or I did not use Docker)

### Describe the bug

Getting "Status NotSupported" under the Intro Skipper0.1.18.0 plugin

Jellyfin version: 10.9.11
Intro Skipper version: 0.1.18.0

jellyfin config: 
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel|ghcr.io/intro-skipper/intro-skipper-docker-mod
    volumes:
      - /<my media location>/movies:/data/movies
      - /<my media location>/tvshows:/data/tvshows
      - /<my media location>/jellyfin:/config
    devices:
    - /dev/dri/renderD128:/dev/dri/renderD128 #optional
    - /dev/dri/card0:/dev/dri/card0
    ports: # plex
      - 8096:8096 # plex
    restart: unless-stopped
--------------------------------------------
File permissions:
i.e nova is my username

drwxr-xr-x  2 nova nova 4096 Sep 20 00:27 books
drwxr-xr-x  2 nova nova 4096 Sep 24 15:07 downloads
drwxr-xr-x 10 nova nova 4096 Sep 24 15:07 movies
drwxr-xr-x  6 nova nova 4096 Sep 20 18:13 tvshows
--------------------------------------------
![image](https://github.com/user-attachments/assets/c43bb611-530e-4cab-951b-31a5d87b9f19)
![image](https://github.com/user-attachments/assets/862a81f2-058e-4031-89dd-79d39dfc9589)

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

lscr.io/linuxserver/jellyfin:latest; Jellyfin version: 10.9.11

### Operating System

Debian 12

### Support Bundle

```shell
my plugin > into skipper > 
"Alert
This plugin has no settings to set up."
```

**Comment by jumoog** [comment]
Install `v1.0.0.1`

**Comment by jumoog** [comment]
You use `https://raw.githubusercontent.com/intro-skipper/intro-skipper/master/manifest.json` ?

**Comment by Samk19** [comment]
https://raw.githubusercontent.com/intro-skipper/intro-skipper/10.8/manifest.json the repository link is this on my jellyfin server

**Comment by AbandonedCart** [comment]
Replace 10.8 with master

**Comment by Samk19** [comment]
yes thanks using @jumoog link and it is working.
Thankyou everyone for your support.
