### ISSUE TITLE
[Bug]: Status not supported

### ISSUE THREAD

**Issue by katsukami213** [intro-skipper/intro-skipper#349]
### Self service debugging

- [X] I use Jellyfin 10.9.11 (or newer) and my permissions are correct

### Describe the bug

![Capture](https://github.com/user-attachments/assets/66ec1cbd-dc4d-4556-8147-d5aab67ca02a)

Is there different thing happening ti was working on windows but not on truenas

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

na

### Operating System

Truenas

### Support Bundle

```shell
NA
```

**Comment by rlauuzo** [comment]
You need to update the repository URL to `https://manifest.intro-skipper.workers.dev/manifest.json`.

**Comment by AbandonedCart** [comment]
If that doesn't solve it, you may actually have to fill in the form next time. There's only so much support that's possible from an error message and the OS name.

**Comment by jumoog** [comment]
How did you even install our oldest release? It's not available through any official channel.

**Comment by jumoog** [comment]
My guess is that you used `https://github.com/ConfusedPolarBear/intro-skipper/blob/master/manifest.json` ?
