### ISSUE TITLE
[Bug]: button does not display, perhaps because two videoOsdPage elements exist?

### ISSUE THREAD

**Issue by captmicr0** [intro-skipper/intro-skipper#358]
### Self service debugging

- [X] I use Jellyfin 10.10.0 (or newer) and my permissions are correct

### Describe the bug

Updated my linuxserver jellyfin to 10.10 (released just a few hours ago), and the intro skip button no longer appears.
Investigating the page source, I saw that when you play a video, a second videoOsdPage element appears.

This second videoOsdPage element seems to be the actual displayed OSD, while the first one stays hidden. This first hidden videoOsdPage element is the one that contains the injected button. Therefore, the button never appears.

I've attached an image of the page's source, specifically the videoOsdPage's parent element, showing both videoOsdPage elements with the same elementID.
![2024-10-26 23_32_15-South Park — Mozilla Firefox](https://github.com/user-attachments/assets/5020f664-e5a3-4c31-954f-02f4b0af3e75)

From what I can tell the intro skip button is added properly, but for some reason when you play any video a second videoOsdPage element is created, with the exact same elementID. This newly created videoOsdPage obviously does not have the intro skip button because it was injected into the original videoOsdPage element.

I also attempted to force skip the intro by calling introSkipper.doSkip() in the console, which resulted in another error.
```
>> introSkipper.doSkip();
[intro skipper] doSkip() called without an active segment
```

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

lscr.io/linuxserver/jellyfin:latest

### Operating System

Ubuntu 22.04.4 LTS (GNU/Linux 6.5.11-060511-generic x86_64)

### Support Bundle

```shell
* Jellyfin version: 10.10.0
* Plugin version: 1.10.10+1019cc30fbcf
* Queue contents: 17115 episodes, 988 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```

### Jellyfin logs
```
[22:53:54] [INF] [1] IntroSkipper.Plugin: Skip button added successfully.
[22:53:54] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Intro Skipper 1.10.10.1
```

**Comment by AbandonedCart** [comment]
Actually, Jellyfin decided that the button is set by the clients in 10.10. You need to open the playback page of the client settings for each client and set how skipping should be handled.

**Comment by rlauuzo** [comment]
I just tried it and encountered the same two `videoOsdPage` instances as well. Disabling the skip button, restarting Jellyfin, then re-enabling the skip button and restarting Jellyfin again seemed to fix it.

**Comment by AbandonedCart** [comment]
That's assuming you also keep the plugin's button enabled and don't enable any of the 10.10 skip functionality.

**Comment by jumoog** [comment]
Maybe a cache problem?

**Comment by AbandonedCart** [comment]
This may require changing the preference name to force resetting it to false. The only way the button should still be enabled automatically going into 10.10 would be if the server was migrated from 10.9

**Comment by captmicr0** [comment]
> I just tried it and encountered the same two `videoOsdPage` instances as well. Disabling the skip button, restarting Jellyfin, then re-enabling the skip button and restarting Jellyfin again seemed to fix it.

Thank you for this tip, seems to have worked and got rid of the duplicate videoOsdPage element.

I also didn't realize that Jellyfin 10.10 has its own intro skip button, which was causing some confusion when I had two Skip Intro buttons showing. I decided to just disabled this plugins button.
