### ISSUE TITLE
[Bug]: manifest bad redirection

### ISSUE THREAD

**Issue by Archer-Tatsu** [intro-skipper/intro-skipper#359]
### Self service debugging

- [X] I use Jellyfin 10.10.0 (or newer) and my permissions are correct

### Describe the bug

https://manifest.intro-skipper.org/manifest.json now is redirected to https://github.com/intro-skipper/. If set in Jellyfin plugin repo, the plugin list cannot be loaded.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:latest

### Operating System

Synology 7.2.2

### Support Bundle

```shell
Can be reproduced just with a browser
```

**Comment by AbandonedCart** [comment]
It redirects to https://github.com/intro-skipper/intro-skipper/blob/10.10/manifest.json, https://github.com/intro-skipper/intro-skipper/blob/10.9/manifest.json, or https://github.com/intro-skipper/intro-skipper/blob/10.8/manifest.json depending on your jellyfin version. What you are seeing is the redirect in a browser, which is meant to go to the repo.

**Comment by Archer-Tatsu** [comment]
> It redirects to https://github.com/intro-skipper/intro-skipper/blob/10.10/manifest.json, https://github.com/intro-skipper/intro-skipper/blob/10.9/manifest.json, or https://github.com/intro-skipper/intro-skipper/blob/10.8/manifest.json depending on your jellyfin version. What you are seeing is the redirect in a browser, which is meant to go to the repo.

if I manually set the repo to https://github.com/intro-skipper/intro-skipper/blob/10.10/manifest.json, the plugin list shows but without Intro Skipper.
![image](https://github.com/user-attachments/assets/167e03d1-56bf-4785-96aa-78c5a0ccea49)

If I set it to https://raw.githubusercontent.com/intro-skipper/intro-skipper/refs/heads/10.10/manifest.json, everything works fine
![image](https://github.com/user-attachments/assets/bc7fdf52-6d4e-46fd-9fa0-172264e3feb4)

If I set it to https://manifest.intro-skipper.org/manifest.json, the list well never stop refreshing.
![image](https://github.com/user-attachments/assets/122fbbe5-7645-42da-8526-1785964dd09d)

**Comment by AbandonedCart** [comment]
https://github.com/intro-skipper/intro-skipper/blob/10.10/manifest.json isn't compatible with jellyfin. I probably should have been more clear that it redirects to the same manifest that can be viewed at those links.

**Comment by jumoog** [comment]
Ahh do you know what's your User-Agent header?

**Comment by jumoog** [comment]
Let me see if I can test this somehow. I guess you are not located in hong kong?

**Comment by Archer-Tatsu** [comment]
No, I'm located in mainland China. However, there is an proxy on my router so that I can access oversea contents. The Jellyfin server is installed on my Synology NAS. Is there any way to get the UA you mentioned? Does it help that the UA of my PC browser?

**Comment by jumoog** [comment]
Ok thats the problem! Please use `https://raw.githubusercontent.com/intro-skipper/intro-skipper/refs/heads/10.10/manifest.json`

**Comment by jumoog** [comment]
The disadvantage of this is that you will have to manage the repo URL yourself. Sorry for the inconvenience

**Comment by jumoog** [comment]
Is this translation right? 

> 如果您来自中国大陆，您需要使用： `https://raw.githubusercontent.com/intro-skipper/intro-skipper/10.10/manifest.json`
