### ISSUE TITLE
[Bug]: Google Cast not Supported

### ISSUE THREAD

**Issue by DarkNeroXIII** [intro-skipper/intro-skipper#363]
### Self service debugging

- [X] I use Jellyfin 10.10.0 (or newer) and my permissions are correct

### Describe the bug

As soon as i apply the fix from the Troubleshooting "chown jellyfin /usr/share/jellyfin/web/index.html" and restarting the container i am able to skip intros but i cannot use the Cast anymore. Neither on Browser nor on Mobile App (browser "Google Cast not Supported" on Mobile app as soon as i press the cast button its spinning and nothing happens.
I made sure that this only happens when i apply the fix because as soon as i return with "chown roon /usr/share/jellyfin/web/index.html" to the previous state Casting works just fine

(i hope i did everything correctly, this is my first Bugreport ever on Github)

### Jellyfin install method

Proxmox Container baremetal without docker

### Container image/tag or Jellyfin version

10.10.0

### Operating System

Debian GNU/Linux 12

### Support Bundle

```shell
* Jellyfin version: 10.10.0
* Plugin version: 1.10.10+ccdea752ef76
* Queue contents: 15986 episodes, 857 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by AbandonedCart** [comment]
Seeing as you are using 10.10, you could simply disable the button included with the plugin and instead use the one included with jellyfin.

You could also try changing the owner of the entire folder containing the index, but that will only work if the cast code is sitting alongside the index.

**Comment by rlauuzo** [comment]
I can't reproduce this on Docker. After you reverted the permissions, the skip button still works, correct?

**Comment by DarkNeroXIII** [comment]
Right now i am absolutely confused i have to say. Right now i did not change anything (Jellyfin 10.10. + Plugin installed + reverted permissions) and the mobile app again startet behaving like it cannot connect to any cast device.

Restoring a 10.09 Jellyfin backup before any changes happaned and checking again

**Comment by AbandonedCart** [comment]
It’s entirely possible cast broke for a different reason. It is notoriously buggy.

**Comment by DarkNeroXIII** [comment]
Back at 10.09. and the App is again able to Cast. I am now doing all steps again but without the permissions thing. Will post an update as soon as the scans are done (might take a while)

**Comment by AbandonedCart** [comment]
Sounds like a plan. Good luck!

**Comment by DarkNeroXIII** [comment]
Update: Looks like i was wrong, i am sorry. The problem seems not to be the Intro Skipper Plugin.
As soon as i upgrade to Jellyfin 10.10. and wait some minutes the Cast stops working. I just cannot figure out why tho

**Comment by DarkNeroXIII** [comment]
Conclusion: Jellyfin 10.10. does cause the Cast issue not the Plugin, sorry for the wrong bug report!

There is a thread within the jellyfin github here about this: https://github.com/jellyfin/jellyfin-android/issues/1501
