### ISSUE TITLE
 [Bug]: Seperate Skip intro and Next buttons.

### ISSUE THREAD

**Issue by xAphex** [intro-skipper/intro-skipper#366]
I never skip the credits and i hate how the Intro-skipper `Next` button overrides jellyfin's next up card.

can you separate the skip intro button and credit button?

![image](https://github.com/user-attachments/assets/52e10853-6613-4b11-9031-21a8f55e29c4)

and thank you for maintaining the plugin ❤️

**Comment by jumoog** [comment]
Jellyfin 10.10.0? If yes this will be fixed in 10.10.1 https://github.com/jellyfin/jellyfin-web/commit/3311a1407f7f6cf2c802afdf1f6086d21192a374

**Comment by xAphex** [comment]
> Jellyfin 10.10.0? If yes this will be fixed in 10.10.1 [jellyfin/jellyfin-web@3311a14](https://github.com/jellyfin/jellyfin-web/commit/3311a1407f7f6cf2c802afdf1f6086d21192a374)

yup jellyfin 10.10.0, guess i will wait for the new jellyfin, thank you for fast reply

**Comment by xAphex** [comment]
![image](https://github.com/user-attachments/assets/0f2b5a01-b6c5-4703-934b-4fe78f9c285c)
jellyfin 10.10.1 with the apparent fix

**Comment by se7entynine** [comment]
@xAphex Is this the same as your bug or another one? There are two buttons for the same functionality in the Jellyfin Media Player for windows. Jellyfin for Android TV is fine.

![grafik](https://github.com/user-attachments/assets/01ff5c35-3e5a-4d1f-b04a-934b9260cf7e)


```
* Jellyfin version: 10.10.1
* Plugin version: 1.10.10+247a5793d806
* Queue contents: 3071 episodes, 256 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```

**Comment by AbandonedCart** [comment]
> Is this the same as your bug or another one? 

That’s actually not a bug. You have both the plugin and the Jellyfin buttons enabled. You need to pick one and disable the other.

**Comment by joshrandall8478** [comment]
> > Is this the same as your bug or another one?
> 
> That’s actually not a bug. You have both the plugin and the Jellyfin buttons enabled. You need to pick one and disable the other.

Jellyfin made the change to have the client side button on by default. I am trying to find a way to make it disabled by default for all users globally.

**Comment by AbandonedCart** [comment]
> Jellyfin made the change to have the client side button on by default. I am trying to find a way to make it disabled by default for all users globally.

You have to disable that one individually

**Comment by joshrandall8478** [comment]
I am aware. Could i make a feature request to make it to where the server owner can set defaults to that setting, or customize the button in a way? The old settings worked better for my instance. I understand if others benefit from this change, but it would be great if we could control these setting defaults in the admin panel.

**Comment by jumoog** [comment]
Do you want to disable the Jellyfish button or the Plugin button?

**Comment by AbandonedCart** [comment]
> I am aware. Could i make a feature request to make it to where the server owner can set defaults to that setting, or customize the button in a way? The old settings worked better for my instance. I understand if others benefit from this change, but it would be great if we could control these setting defaults in the admin panel.

That request would need to be made to Jellyfin. They implemented their button on a per-client basis with a per-client setting. They are also rather persistent about not wanting any more settings than absolutely necessary and not wanting them to be centralized.

**Comment by joshrandall8478** [comment]
I want the client side button disabled by default, like in 10.10.0. and it’s okay, i’ll find a way :)

**Comment by AbandonedCart** [comment]
> I want the client side button disabled by default, like in 10.10.0. and it’s okay, i’ll find a way :)

You can rebuild it without https://github.com/jellyfin/jellyfin-web/pull/6266 for the web server, but other clients may not separate the change so neatly.

**Comment by xAphex** [comment]
> ![image](https://private-user-images.githubusercontent.com/5391237/382917288-0f2b5a01-b6c5-4703-934b-4fe78f9c285c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDU4MzAsIm5iZiI6MTczMjY0NTUzMCwicGF0aCI6Ii81MzkxMjM3LzM4MjkxNzI4OC0wZjJiNWEwMS1iNmM1LTQ3MDMtOTM0Yi00ZmU3OGY5YzI4NWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMTgyNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY1NTM2ZDRlYjhmZjdhNGQ2MTNhODU3MTY5YmMwMzhjZGZmNTE3YzM0ODllZWEwZmFlMmVkODM3MzllNzk4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Pt5RqDimGCmzrFDNi3hd0BVOApacJeEhvxW6xFg5whg) jellyfin 10.10.1 with the apparent fix

Same thing happening with `v1.10.10.11`
