### ISSUE TITLE
Skip if no interaction

### ISSUE THREAD

**Issue by LegandaryRa** [intro-skipper/intro-skipper#367]
Hi,
thanks for the awesome plugin.

It would be great if the skip button says skipping 5 - 4 - 3 - 2 - 1 Press to cancel.
If you want to watch the Intro you then click and if not it automatically skips.

**Comment by AbandonedCart** [comment]
You have the option to press the button or auto skip, but adding an option to auto skip when not pressing the button would be extremely messy, especially with jellyfin trying to take over the skipping part of the process.

**Comment by LegandaryRa** [comment]
thanks for your response.

This seems like a good reason to not implement it. But it still would be nice to have.

BR
