### ISSUE TITLE
[Bug]: The Skip Intro button does not appear on Android TV (latest beta)

### ISSUE THREAD

**Issue by itsrn** [intro-skipper/intro-skipper#369]
### Self service debugging

- [X] I use Jellyfin 10.10.0 (or newer) and my permissions are correct

### Describe the bug

I'm using Jellyfin's latest version and the latest Android TV beta (from the github releases). 

When trying to play an episode that has segments (that are shown on the web version of jellyfin) on the Android TV version (the latest beta version, the one that also has the new options for the playback like in the web version), the buttons do not appear.

I've set the "Show skip intro / credit button" option in the plugin enabled, along with the new option in Jellyfin web (and in the Android TV beta) "Ask to skip" in the Playback settings for introductions and credits.

Maybe it's because there is a conflict between the plugin option "Show skip intro / credit button" and the option in the client itself to "Ask to skip"?

### Jellyfin install method

Jellyman

### Container image/tag or Jellyfin version

Jellyfin: 10.10.1, IntroSkipper: 1.10.10.2

### Operating System

Debian 11

### IMDb ID of that TV Series

None

### Support Bundle

```shell
* Jellyfin version: 10.10.1
* Plugin version: 1.10.10+ccdea752ef76
* Queue contents: 2119 episodes, 123 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 14.1.0 (crosstool-NG 1.26.0.93_a87bf7f)
configuration: --prefix=/ffbuild/prefix --pkg-config=pkg-config --pkg-config-flags=--static --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --extra-version=Jellyfin --extra-cflags= --extra-cxxflags= --extra-ldflags= --extra-ldexeflags=-pie --extra-libs=-ldl --enable-gpl --enable-version3 --enable-lto --disable-ffplay --disable-debug --disable-doc --disable-ptx-compression --disable-sdl2 --disable-libxcb --disable-xlib --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-amf --enable-chromaprint --enable-libdav1d --enable-libfdk-aac --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpl --enable-libvpx --enable-libwebp --enable-libopenmpt --disable-rkmpp --disable-rkrga --enable-libsrt --enable-libsvtav1 --enable-libdrm --enable-vaapi --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libzimg --enable-libzvbi
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by jumoog** [comment]
`Show skip intro / credit button` is the option for the plugin button. If you want use official `segments` you need to set segment options per client.
