### ISSUE TITLE
[Bug]: User Interface Customization feature does not work

### ISSUE THREAD

**Issue by KimPig** [intro-skipper/intro-skipper#371]
### Self service debugging

- [X] I use Jellyfin 10.10.1 (or newer) and my permissions are correct

### Describe the bug

I don't remember what the update was, but after the update that changed the UI, the User Interface Customization function does not work as shown in the picture below. This also applies to version 1.10.10.3, which was updated yesterday.

![image](https://github.com/user-attachments/assets/792eeff4-feeb-4a06-a53a-b63da8a6f919)
![image](https://github.com/user-attachments/assets/dddc73dc-fc30-49ce-a329-6ba5c7a05ae7)

### Jellyfin install method

Windows

### Container image/tag or Jellyfin version

Jellyfin Windows 10.10.1

### Operating System

Windows 10

### Support Bundle

```shell
* Jellyfin version: 10.10.1
* Plugin version: 1.10.10+71768972e5ef
* Queue contents: 16291 episodes, 961 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with clang version 18.1.8
configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by AbandonedCart** [comment]
You're customizing the plugin's injected button and using the Jellyfin native button. They don't offer customization at this time.

**Comment by KimPig** [comment]
Oh, I just found out that Media Segments are working after the update. We apologize for any confusion.
However, even if I check the Show All Skip Buttons item and restart the server, it is always unchecked. What's the problem?

![image](https://github.com/user-attachments/assets/9e346819-1c52-497c-b466-8428aa35abec)

**Comment by AbandonedCart** [comment]
https://github.com/intro-skipper/intro-skipper/wiki/Troubleshooting#skip-button-is-not-visible

**Comment by KimPig** [comment]
Since I'm using Windows, I've already checked for permission issues. 
In addition, the skip button appeared without any problems until Jellyfin's update. Even if I check the button, it will still be unchecked when I restart the server.
Instead, I found an error in the log. Could this be relevant to my current situation?
For reference, my jellyfin-web version is 10.10.1.


```
[2024-11-05 19:50:30.423 +09:00] [WRN] [1] IntroSkipper.Plugin: Something stupid happened: "System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\plugins\configurations\ConfusedPolarBear.Plugin.IntroSkipper.xml' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at IntroSkipper.Plugin..ctor(IApplicationHost applicationHost, IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)"
[2024-11-05 19:50:30.499 +09:00] [INF] [1] IntroSkipper.Plugin: Found jellyfin-web <"10.9.6">
[2024-11-05 19:50:30.500 +09:00] [WRN] [1] IntroSkipper.Plugin: The jellyfin-web <"10.9.6.0"> NOT compatible with Jellyfin <"10.10.1.0">
```

![image](https://github.com/user-attachments/assets/faac7e7a-c2f0-47e4-aaf1-1c7449f8b682)

**Comment by AbandonedCart** [comment]
You have an old copy of a web client installed.

**Comment by KimPig** [comment]
It works normally after deleting ConfusedPolarBear.Plugin.IntroSkipper.xml. thank you for your reply

**Comment by AbandonedCart** [comment]
Glad to hear that fixed it.
