### ISSUE TITLE
[Bug]: Automatic skip happens even if not enabled

### ISSUE THREAD

**Issue by drilus** [intro-skipper/intro-skipper#375]
### Self service debugging

- [X] I use Jellyfin 10.10.1 (or newer) and my permissions are correct

### Describe the bug

I have automatic skip disabled in both the plugin settings and playback settings. Yet, intro's still get automatically skipped. Toggling auto skip doesn't fix the issue either.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

10.10.1

### Operating System

Docker/Linux

### Support Bundle

```shell
* Jellyfin version: 10.10.1
* Plugin version: 1.10.10+f68fd9d06af0
* Queue contents: 4089 episodes, 314 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
Did you disable it in the player menu?

https://github.com/user-attachments/assets/5f93fe4d-f1b5-47b9-a253-9e0815ceec31

**Comment by AbandonedCart** [comment]
Have you also made sure the client isn’t set to auto skip?
(Under the playback section of the plugin settings page)

**Comment by drilus** [comment]
> Did you disable it in the player menu?

I don't have that option in the player menu

> Have you also made sure the client isn’t set to auto skip?
> (Under the playback section of the plugin settings page)

It's not set to auto skip.

**Comment by jumoog** [comment]
I have this problem too. I'll look into it.

**Comment by jumoog** [comment]
It looks like there is a problem. When I update my config, sometimes the config file is not updated.

**Comment by jumoog** [comment]
I takes some time.. very strange

**Comment by jumoog** [comment]
When I disable auto skip for credits and intro (there are two separate options) it works. I still had credits enabled.

**Comment by drilus** [comment]
> It looks like there is a problem. When I update my config, sometimes the config file is not updated.

Where is the config file stored?

**Comment by drilus** [comment]
For some reason the "Auto Skip Client List" was selected for all my devices. The description text is misleading IMO.

"Clients enabled in this list will always skip automatically, regardless of the button settings below." suggests, to me, it only applies to the options below it (Automatically Skip Intros and Automatically Skip Credits are above the setting).

Instead of those options being in their own category why not making it a selection for Automatically Skip Intros? When selecting to automatically skip intro's you have the option to either select the individual device/client.

**Comment by AbandonedCart** [comment]
> "Clients enabled in this list will always skip automatically, regardless of the button settings below." suggests, to me, it only applies to the options below it (Automatically Skip Intros and Automatically Skip Credits are above the setting).

It sounds like you overlooked the word **regardless** that implies the setting below will not change it.

**Regardless**, the wording and options themselves have all been changed in the current PR in progress.

Edit: This was meant to be a pun. We are aware of the confusing nature of the current layout.
