### ISSUE TITLE
[Bug]: Failed to add skip button

### ISSUE THREAD

**Issue by kabatp** [intro-skipper/intro-skipper#380]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

The skip button does not show up at any of the Jellyfin clients including

- web
- official Android TV app
- official Android app

### Jellyfin install method

TrueNas Scale 24.10 Apps

### Container image/tag or Jellyfin version

jellyfin/jellyfin 10.10.2

### Operating System

TrueNas Scale 24.10

### Support Bundle

```shell
* Jellyfin version: 10.10.2
* Plugin version: 1.10.10+f275e188da52
* Queue contents: 2865 episodes, 465 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
Enable `Regenerate Media Segments on Next Scan`, then manually start the Scan Intro and Credits task that should fix the issue.
![grafik](https://github.com/user-attachments/assets/33f7e960-42c4-4a0c-aad1-45c0ca8d5b62)

**Comment by kabatp** [comment]
This option was enabled by default. I reran the scan and restarted Jellyfin via Dashboard and the result is following:

- Web client is showing the skip button but the error in the plugin settings is still there
- Android app is showing the button correctly
- Android TV app even after complete reset is not showing the button

**Comment by rlauuzo** [comment]
The warning in the settings can ignored. For Android TV, ensure you're using the latest beta, v0.18.0-beta.3, to enable skip button.

**Comment by kabatp** [comment]
Than you, the switch to beta version solved the issue. I must be blind, but this has to be mentioned in troubleshooting of Android TV APP!
