### ISSUE TITLE
[Feature Request] Separate the option for TV and Movies

### ISSUE THREAD

**Issue by Hello-World-Traveler** [intro-skipper/intro-skipper#382]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

Separate the option for TV and Movies for skipping. You might want TV shows to auto skip but not movies as there might be some parts of the movie in the credits.

Have something like:

![Screenshot 2024-11-19 at 19-27-35 Plugins](https://github.com/user-attachments/assets/f6bf830c-f402-4c71-97c7-553ce704bc45)

Also the Analyze Movies option, there should be text under explaining what it does. Does it only work on credits?
`If enabled, Movies will be automatically be analyzed for credits using [something]`

### Jellyfin install method

N/A

### Container image/tag or Jellyfin version

10.10.2

### Operating System

N/A

### Support Bundle

```shell
N/A
```

**Comment by AbandonedCart** [comment]
Are they in the same library? An easy way to accomplish this would be using separate libraries and simply not skipping for one of them. 

Adding a setting to detect if an item is a movie is possible, but television shows and other videos are harder to differentiate. Also, in the case of OVAs (anime), it could technically be either. It's quite possible it could end up inconsistent.

**Comment by Hello-World-Traveler** [comment]
Separate libraries. Skipping for tv but not movies would be the ideal goal.

Or having the skip button active within the last 10 minutes of the movie (black screen detection) and stay until the end?

**Comment by AbandonedCart** [comment]
> Separate libraries.

Disable skipping for the movie library

**Comment by Hello-World-Traveler** [comment]
Automatically Skip Credits has already  been unticked and Automatically Skip Intros is ticked.

Have I missed something?

**Comment by AbandonedCart** [comment]
Uncheck Enable analysis for all libraries containing television episodes
Make sure the movie library is unchecked.

**Comment by Hello-World-Traveler** [comment]
Enable analysis for all libraries containing television episodes is already  unticked, only TV shows are ticked.
Analyse Movies is ticked

**Comment by AbandonedCart** [comment]
> Analyse Movies is ticked

Probably not something you need if you don't want to skip on movies

**Comment by Hello-World-Traveler** [comment]
Movies don't skip at all. 

My feature request is to separate the option to automatically Skip credits into two options, Tv  and/or Movies.

**Comment by AbandonedCart** [comment]
> My feature request is to separate the option to automatically Skip credits into two options, Tv and/or Movies.

Adding a setting to detect if an item is a movie is possible, but television shows and other videos are harder to differentiate. Also, in the case of OVAs (anime), it could technically be either. It's quite possible it could end up inconsistent.

This means that adding an option like that will likely create more problems than it will solve.

**Comment by Hello-World-Traveler** [comment]
>This means that adding an option like that will likely create more problems than it will solve

That's not something anyone wants, is there a solution for this request without creating more problems? we can close this for the time being.

**Comment by jumoog** [comment]
Our autoskip settings have no effect on your media segement settings. We send a seek command to the client. If you enabled skipping in the jellyfin client settings for media segment actions this will always happens.

**Comment by AbandonedCart** [comment]
> That's not something anyone wants, is there a solution for this request without creating more problems? we can close this for the time being.

The big problem is that once you create the timestamps, it is hard to remove them automa… I just had an idea. I’ll be back.

**Comment by Hello-World-Traveler** [comment]
@jumoog JF Android tv  0.18 beta has support for media segments, it's now possible for the client  to auto skip or ask the user. I have it on ask however I don't have the Jellyfin media segment plugin installed.

@AbandonedCart An idea or two ideas? 👍

**Comment by AbandonedCart** [comment]
> JF Android tv 0.18 beta has support for media segments, it's now possible for the client to auto skip or ask the user. I have it on ask however I don't have the Jellyfin media segment plugin installed.

This plugin provides the necessary segments.

**Comment by Hello-World-Traveler** [comment]
I am aware of that and I am also aware that plugin doesn't play well with others for the time being.
It's nice that the client supports media segments.

It has been nice watching this plugin grow the way it has. The team such as yourself has and is doing well.

**Comment by AbandonedCart** [comment]
We shouldn’t need this option in future releases. We’ll be passing off the selection to Jellyfin, so you’ll be able to exclude movies right through the normal UI

**Comment by Hello-World-Traveler** [comment]
This plugin will only focus on tv shows moving forward?

**Comment by AbandonedCart** [comment]
> This plugin will only focus on tv shows moving forward?

No. Movies will be enabled or disabled by the server settings.

**Comment by Hello-World-Traveler** [comment]
I misunderstood what you said. Are you saying that soon we would be changing settings within jellyfin itself meaning that the user will not have to go to My plugins -> Intro-skipper -> settings for changing some or all the settings?
