### ISSUE TITLE
[Bug]: The skip outro button is not showing up

### ISSUE THREAD

**Issue by Jacob-077** [intro-skipper/intro-skipper#385]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

The skip outro button is not showing up on the screen despite the correct detection:

<img width="579" alt="Screenshot_3" src="https://github.com/user-attachments/assets/2e7c66f4-488a-40c4-85d2-5ef0d02bbb69">

For some shows it appears, and for some others, it only shows for one episode but not the second, again all with correct detection values in the settings.

Could I be doing something wrong for this inconsistent behavior to occur?

On a side note, I read some posts on a setting called "Play intro for first episode of a season", however, I don't see that option anywhere. Was it removed?

### Jellyfin install method

Windows installer

### Container image/tag or Jellyfin version

Jellyfin 10.10.3

### Operating System

Window 10

### IMDb ID of that TV Series

tt12637874

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+f275e188da52
* Queue contents: 1632 episodes, 189 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with clang version 19.1.3
configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by AbandonedCart** [comment]
Does the outro go until the end of the video?

**Comment by Jacob-077** [comment]
Yes, there's credits text up until the very last second.

**Comment by AbandonedCart** [comment]
I made a similar report to Jellyfin and later discovered it to be nothing more than confusion about how it works. When the two ending options collide, the next video info option gets prioritized. You can either disable "Show next video info during playback" directly above the segment options or wait a little extra for the next video dialog to appear.

**Comment by Jacob-077** [comment]
Just to be sure, that option is what enables this pop-up, correct?

<img width="375" alt="Screenshot_4" src="https://github.com/user-attachments/assets/afc259cb-e7a6-4bdf-8a62-11ca14c64433">

If yes, I can confirm that disabling this setting makes the outro button appear. Thanks, [AbandonedCart](https://github.com/AbandonedCart)!

**Comment by jumoog** [comment]
I'll close this issue because it's not a plugin issue.

**Comment by Jacob-077** [comment]
@jumoog instead of opening a new issue, I wanted to quickly ask, was the "Play intro for first episode of a season" option removed from the plugin? Because I can't find it anywhere.

**Comment by jumoog** [comment]
This option works only with the injected plugin button

**Comment by Jacob-077** [comment]
How to enable that? I went through all the settings and documentation and there's no mention of an "injected button" except for [here](https://github.com/intro-skipper/intro-skipper/wiki/Troubleshooting), but still, there are no instructions on how to enable that unless it's strictly for 10.9 and older versions.

**Comment by AbandonedCart** [comment]
In 10.10.X, it's not really recommended. A lot of the support is still being rolled out and changing now will just make it a hassle to change back later.

**Comment by jumoog** [comment]
Maybe we can implement it for media segment api as well
