### ISSUE TITLE
[Bug]: Manifest URL is not woring

### ISSUE THREAD

**Issue by istvandocsa** [intro-skipper/intro-skipper#386]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

I have tried to set up the plugin through README manifest url: `https://manifest.intro-skipper.org/manifest.json` which did not resolve it. Opening it just points to the github org landing page.
I referenced the manifest directly as `https://raw.githubusercontent.com/intro-skipper/intro-skipper/refs/heads/10.10/manifest.json` which worked as expected. (the plugin is great btw, thank you!)

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:latest

### Operating System

Ubuntu Server 24.04

### Support Bundle

```shell
Not applicable
```

**Comment by jumoog** [comment]
The URL only works with Jellyfin. Cloudflare will redirect you to the correct manifest based on the Jeyllfin version. Everyone else gets redirected to the GitHub Org.

Does this works for you?

```
curl -A "Jellyfin-Server/10.10.2" https://manifest.intro-skipper.org/manifest.json -L
```

**Comment by jumoog** [comment]
This is the background for the redirect: https://github.com/intro-skipper/manifest-worker?tab=readme-ov-file#why

**Comment by jumoog** [comment]
If the curl command doesn't work, you're being blocked by cloudflare.
