### ISSUE TITLE
[Feature Request]: Skip entire libraries

### ISSUE THREAD

**Issue by Noodlez1232** [intro-skipper/intro-skipper#387]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

I have a library that I use for Youtube videos that I'd like to skip, since I have it automatically pulling out SponsorBlock entries as chapters that then become media segments using the builtin chapter detector.

After running this plugin it clobbered all of those media segments that Jellyfin refuses to overwrite (and I feel rightfully so).

This wouldn't have happened if I could blacklist the library. As of right now, you *can* ignore certain series and their seasons, but I have hundreds of channels archived, each having an average of 3 or 4 seasons.

I'd like it to be simpler to ignore entire series and even entire libraries, perhaps as an edition to the metadata management screen and library management screen.

### Jellyfin install method

NixOS

### Container image/tag or Jellyfin version

jellyfin

### Operating System

NixOS

### IMDb ID of that TV Series

blah

### Support Bundle

```shell
unimportant
```

**Comment by jumoog** [comment]
![grafik](https://github.com/user-attachments/assets/85c3c786-e2ef-4543-a70c-06439c85fab1)

**Comment by jumoog** [comment]
just go into the plugins settings and uncheck  `Enable analysis for all libraries containing television episodes`. Then you can pick which libraries you want to scan.

**Comment by Noodlez1232** [comment]
Sorry this wasn't really obvious from the description that it would work this way. Thanks for the info!

**Comment by jumoog** [comment]
Yes this will be simpler soon #384
