### ISSUE TITLE
[Bug]: Jellyfin 10.10's MediaSegment's Api not returning Intro and Outro info

### ISSUE THREAD

**Issue by prayag17** [intro-skipper/intro-skipper#388]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

Hello, I am working on a Jellyfin client called Blink and I was working on moving the Intro/Credits info fetching api from intro-skipper's api to the newly introduced MediaSegments api... but it does not seem to return any intro or outro data. I was also not able to find documentation for MediaSegmentsApi otther than the official jellyfin typescript-sdk.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:10.10.2

### Operating System

Debian 11

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+f275e188da52
* Queue contents: 4000 episodes, 219 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
The MediaSegments API documentation is available [here](https://api.jellyfin.org/#tag/MediaSegments). 

If you're not seeing intro or outro data, ensure that you’ve run the Intro Skipper scheduled task with the "Regenerate MediaSegment" option enabled. This step resolves a compatibility issue that may arise if an older version of Intro Skipper was previously installed. Without this, the MediaSegments data might not be pulled.

**Comment by prayag17** [comment]
If by "Regenerate Media segments" you mean "Update Segments for New Media During Scan" option I have already enabled it and reran my Detect Intro and Outro task but that still does not change the output

**Comment by AbandonedCart** [comment]
> If by "Regenerate Media segments" you mean "Update Segments for New Media During Scan" option I have already enabled it and reran my Detect Intro and Outro task but that still does not change the output

No. The actual name of the setting is "Regenerate All Media Segments on Next Run" in the "Modify Segment Parameters" box

**Comment by prayag17** [comment]
Ok found it. Thanks for helping me
