### ISSUE TITLE
[Feature Request]Return key event listener so "Skip" button can be triggered with Enter key

### ISSUE THREAD

**Issue by michael-zock** [intro-skipper/intro-skipper#396]
With the move to the native button support in 10.10.0, this feature got lost.
Is there any chance to return this functionality again?

**Comment by jumoog** [comment]
Unfortunately, there's nothing we can do. This is a feature request for Jellyfin.

**Comment by AbandonedCart** [comment]
Just to clarify, the button is no longer injected in 10.10 and is now provided by the client. The plugin sets the timestamps, the server stores them, the client uses them.

**Comment by jumoog** [comment]
> Unfortunately, there's nothing we can do. This is a feature request for Jellyfin.

Or you make a PR to https://github.com/jellyfin/jellyfin-web
