### ISSUE TITLE
[Bug]: Editing timestamps from the config page doesn't work

### ISSUE THREAD

**Issue by QuarkZ26** [intro-skipper/intro-skipper#404]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

I was looking at the "Edit a timestamp" help and see that there is no such section in the metadata so I can't modify anything.

Everything else seems to work though, the detection, skipping and even autoskip work just fine (besides intro skipping going 2s before the actual time showing in the plugin. Edit: I found the reason for this), except that I have no way to modify any of it.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

latest

### Operating System

Arch

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+1048eaf26d7e
* Queue contents: 4959 episodes, 283 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by mihawk90** [comment]
That's not a bug. It just means that it has no permission to edit the index.html which is not unusual in Docker (actually expected).

It's the same thing as with the Skip button:
https://github.com/intro-skipper/intro-skipper/wiki/Troubleshooting#skip-button-is-not-visible

You can still edit timestamps in the Plugin configuration page.

edit:
That said, it should probably be documented

**Comment by QuarkZ26** [comment]
Skip button is perfectly visible for me, also I setup the Docker instance to have the proper user/group permissions. I can access everything else without issue, and everything else works just fine, the detection and skip processes, why would that file be any different? 

Editing timestamps from the config page doesn't seem to work either though, I have tried modifying something in there, and going back to it shows the timestamp as it was before, not sure if I'm missing something. Since again everything else in the plugin seems to work, it seems strange this would not

**Comment by mihawk90** [comment]
> Skip button is perfectly visible for me

Are you sure that's intro-skipper's button and not JF's native skip button?

Either way get a server log after restarting the server, the startup log should be more helpful.

**Comment by AbandonedCart** [comment]
The two second lead is a known issue. You can’t edit the timestamps in meta because injection is no longer required (but also means that menu is no longer injected). Instead, head to the bottom of the plugin settings page to the timestamp and fingerprint editor. There is a slightly less pretty, but equally (if not more) functional editor there.

**Comment by QuarkZ26** [comment]
> The two second lead is a known issue. You can’t edit the timestamps in meta because injection is no longer required (but also means that menu is no longer injected). Instead, head to the bottom of the plugin settings page to the timestamp and fingerprint editor. There is a slightly less pretty, but equally (if not more) functional editor there.

Removing the 2s in "Segment playback duration" in the "Enable injected server-side skip" section, actually got rid of that 2s lead. 

However like I said above, the timestamp editor in the plugin doesn't work for me, it never actually saves the changes that I make

**Comment by AbandonedCart** [comment]
Are you making sure to click save and not manually running a fresh analysis? If you run a new analysis, it can potentially overwrite your custom settings.

**Comment by QuarkZ26** [comment]
I click "Update timestamps" after I make the modifications, but after I swap back and forth it shows the same timestamps as the previous. Testing the file also skips to where it was first detected.

**Comment by AbandonedCart** [comment]
What do you mean by "swap back and forth"?

> Removing the 2s in "Segment playback duration" in the "Enable injected server-side skip" section, actually got rid of that 2s lead.

https://github.com/intro-skipper/intro-skipper/pull/405 will fix that without having to enable the inject option.

**Comment by QuarkZ26** [comment]
i mean switching to a different episode and going back, to see if the values stuck, which they don't, it shows whatever was there before I made the change. When I click it says the timestamps were saved, but they aren't.

**Comment by AbandonedCart** [comment]
The option I would suggest isn't an option yet, so the alternative is the manual way...

If you open your jellyfin data folder, there should be an introskipper folder that contains an introskipper.db. Delete that file and reboot the server. It sounds like there is an issue with writing data to the database.

**Comment by QuarkZ26** [comment]
Still doesn't work unfortunately.

![image](https://github.com/user-attachments/assets/73309ddd-e7af-4e2e-8d22-14294c61fc17)

that db doesn't seem to update indeed. Still those timestamps are saved in the first place, strangely enough. 

Edit: It did end up writing into the db, however the values still stay the same

**Comment by nerethos** [comment]
I have the same issue. Updating timestamps from the plugin settings doesn't do anything. Nothing is logged.

**Comment by QuarkZ26** [comment]
Just for the heck of it, I tested this on a pure Linux OS and Windows OS and it worked on none of them, so it doesn't seem to be OS related.

**Comment by nado** [comment]
For anyone wondering like me:
https://github.com/intro-skipper/intro-skipper/commit/24619a2b00ad63bcc17a9cfa9241a84ba69589cc
