### ISSUE TITLE
[Feature Request] Include an up-to-date list of which clients support intro skip buttons in the documentation.

### ISSUE THREAD

**Issue by nothing2obvi** [intro-skipper/intro-skipper#408]
It would be great if the documentation included a table of all the Jellyfin clients and whether or not they support the intro skip button or other features. I've been asking around on the Jellyfin Forum, but it would be great to have a centralized table to refer to. Otherwise, I think Intro Skipper is awesome!

**Comment by jumoog** [comment]
see https://github.com/orgs/intro-skipper/discussions/409

we don't know all clients

**Comment by nothing2obvi** [comment]
Thanks! That's a start!
