### ISSUE TITLE
[Bug]: No Skip button after upgrade to 10.10 from 10.9

### ISSUE THREAD

**Issue by Kyon147** [intro-skipper/intro-skipper#414]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

Everything was working great but updated to the latest version of Jellyfin today and no the Skip button is no longer showing.

Kicked of the schedule tasks which completed successfully but still nothing.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:latest / intro-skipper:1.10.9.2

### Operating System

Linux

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.9+df28ef8be766
* Queue contents: 7928 episodes, 593 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
You are using an outdated version. Please update the plugin to version 1.10.10.11. Ensure that the repository URL is set to `https://manifest.intro-skipper.org/manifest.json`. Afterward, run the update plugins task and restart Jellyfin.

**Comment by Kyon147** [comment]
@rlauuzo thanks will give that a try!

**Comment by Kyon147** [comment]
Updated but still not showing up, I'll run the scheduled tasks again and leave it and see tomorrow.

**Comment by Kyon147** [comment]
Intro button is back now but I have noticed a new bug. 

Before on the previous version the "Skip Intro" button would be automatically focus when it was there, which is useful to be able just hit enter etc when wathing on PC or TV wihtout having to focus on it yourself.

**Comment by AbandonedCart** [comment]
If it’s the client button, it doesn’t include that feature yet.

**Comment by Kyon147** [comment]
@AbandonedCart thanks for the reply! Is there a way to use the latest version but revert back to the "server" like the version I was using before?

**Comment by AbandonedCart** [comment]
As of today, 10.10.3 is the latest version. 

Enabling the plugin button means having to go through each client and user to disable the new button and potentially dealing with all of the permission issues and such like older versions. It depends on if the feature is really worth the hassle to you.

**Comment by Kyon147** [comment]
Makes sense, I'll just deal with it for now as it is not a huge issue. The plugin however is amazing, thanks for your work on it!
