### ISSUE TITLE
[Feature Request] Exclude Series from scan

### ISSUE THREAD

**Issue by QuarkZ26** [intro-skipper/intro-skipper#418]
Can we have an option to exclude certain series from scans? 

Some might not need it so it would save some computational time. I know you can limit the scan per library, but it would probably be impractical to create separate libraries just for this. I'm thinking going another step down and using "Limit analysis to the following series" might not be too difficult?

**Comment by rlauuzo** [comment]
You can already do this by selecting 'None' as the analyzer.

![grafik](https://github.com/user-attachments/assets/af58f454-a6ca-4753-9dc3-ea4e713d5d54)

**Comment by QuarkZ26** [comment]
This is just painfully difficult, you have to go through each season and unselect everything for each, if you have many Series that contain many seasons, this is just not practical, not even counting the fact if it's ongoing then you have to go in there again for any new season.

Edit: Since you have responded with a "confused" emoji, even though it seems pretty obvious to me :P 

Let's take one example, Family Guy, 22 seasons, I would need to click a total of 132 times to exclude everything (select the season, change each of the 4 options, apply changes, then go to the next) as opposed to...  2 times to exclude the series. And you have to do this all over again for any other series you want to exclude.

Also, from a design perspective, how many times would someone really want to just exclude one particular season instead of a series?

And like I said, doing this doesn't even exclude upcoming seasons, you'd still have to go back in there in each time, granted by that point it's easier, but still, it might start analyzing new stuff by the time you realize a new season started, or you remember it.

**Comment by AbandonedCart** [comment]
It is painfully difficult any way you approach it. One of the biggest hurdles for projects like this is that simple sounding issues don’t always have simple solutions. This is a perfect example.

**Comment by AbandonedCart** [comment]
Had to switch to a keyboard for this...

So the whole process isn't actually that we see you have Family Guy and we see that you have seasons X, Y, Z, etc. and then assign times to them. In reality, the whole editor with all the names and such is purely sourced on the fly by your meta details based on nothing more than an index of a episodes in a season of *some show*. It is grouped together by traversing the meta information, but retrieved as episodes in a season, not episodes in seasons in shows.

**Comment by rlauuzo** [comment]
Is this more to your liking? You can find the setting at the bottom of 'Modify Segment Parameters'.

https://github.com/intro-skipper/intro-skipper/actions/runs/12332397417?pr=419

**Comment by QuarkZ26** [comment]
Not sure if I'm missing something, I don't see any additional settings after overwriting the dll

**Comment by rlauuzo** [comment]
You need to restart Jellyfin after replacing the DLL

**Comment by QuarkZ26** [comment]
I did. Can you screenshot what it's supposed to show?

**Comment by rlauuzo** [comment]
![grafik](https://github.com/user-attachments/assets/2a00c357-3ea8-46f9-ad09-3d8dcf345fe4)

**Comment by QuarkZ26** [comment]
ok, i reinstalled and cleaned a bit, and I see it now, that would be perfect!

**Comment by QuarkZ26** [comment]
Actually I see it's actually completely working already, that's awesome, thank you so much!
