### ISSUE TITLE
[docs]: explained how to add a plugin repository to Jellyfin

### ISSUE THREAD

**Issue by brianjmurrell** [intro-skipper/intro-skipper#423]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

It would be nice if step 1 at https://github.com/intro-skipper/intro-skipper/wiki/Installation#step-1-install-the-plugin explained how to add a plugin repository to Jellyfin, or linked to instructions on how to do that.

### Jellyfin install method

RPM

### Container image/tag or Jellyfin version

10.10.3

### Operating System

Linux

### Support Bundle

```shell
Not installed yet.
```

**Comment by jumoog** [comment]
https://github.com/intro-skipper/intro-skipper/wiki/Installation

**Comment by brianjmurrell** [comment]
That's perfect!  Thanks.
