### ISSUE TITLE
[Feature Request] Allow administrator to pick default skip modes.

### ISSUE THREAD

**Issue by Allerek** [intro-skipper/intro-skipper#426]
Hi, i think it would be nice to allow administrator to change default skip modes.
Also, possibility to change it per-user later on.
For me and my friends - Netflix type of skip (show skip button for intro/recap on default) is well... default. Its annoying to tell all of them how to turn that on.

**Comment by AbandonedCart** [comment]
This is determined by Jellyfin, as the plugin only provides the data about segments.
