### ISSUE TITLE
no skip button on android client

### ISSUE THREAD

**Issue by glenb77** [intro-skipper/intro-skipper#427]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

i have a skip intro button on the web browser interface on same show where it appears and works there is no skip intro button on the android app using nvidia shield pro. 

### Jellyfin install method

docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:latest

### Operating System

docker version; archlinux on server

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+1048eaf26d7e
* Queue contents: 143883 episodes, 10564 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by vajonam** [comment]
Ensure you are running 0.18.2 on Android TV application

**Comment by glenb77** [comment]
yes that was it. i did not pick up 12-7 update. now on current and
indeed button appears. apologies. i will close issue shortly

On Fri, 2024-12-20 at 06:34 -0800, vajonam wrote:
> Ensure you are running 0.18.2 on Android TV application
> —
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>


[1] view it on GitHub
    https://github.com/intro-skipper/intro-skipper/issues/427#issuecomment-2557129850
[2] unsubscribe

**Comment by AbandonedCart** [comment]
No worries. The issue has been closed.
