### ISSUE TITLE
Progress sets to 0:00 after skipping outro

### ISSUE THREAD

**Issue by languagemaniac** [intro-skipper/intro-skipper#436]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

Hi there, I'm running jellyfin via linuxserver docker image, version is 10.10.3

I watch jellyfin via Android tv app

Jellefyin app version: 0.18.2 release

Into playback settings, if outros is set to "Ask to skip", often while pressing OK to skip (when prompted) will cause the next episode to play but:

* The timer will stay at 0:00 while I watch the show
* It will not allow you see where you are at
* It will not save the timestamp if you exit (it will, but it'll be 0:00)
* It disables the option to rewind (jumping to 0:00)

I don't know if this issue is on the plugin side or on Android tv app, any help would be appreciated

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

lscr.io/linuxserver/jellyfin:latest

### Operating System

Debian 11

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+24619a2b00ad
* Queue contents: 2337 episodes, 146 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13 (Ubuntu 13.3.0-6ubuntu2~24.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

```shell
Couldn't find any relevant log
```

**Comment by AbandonedCart** [comment]
The plugin provides the times, but everything else is handled in the app. Do you have valid times for the show?

Open the plugin settings, scroll to the bottom and expand Edit Timestamps & Fingerprints.
Select the show and season to see what timestamps the plugin has saved.

**Comment by languagemaniac** [comment]
> The plugin provides the times, but everything else is handled in the app. Do you have valid times for the show?
> 
> Open the plugin settings, scroll to the bottom and expand Edit Timestamps & Fingerprints. Select the show and season to see what timestamps the plugin has saved.

Yeah the Timestamps are ok, it does skip the outros successfully, the issue must be related with the app then
